version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 82:82
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./php:/var/www/html

  php:
    image: php:latest
    volumes:
      - ./php:/var/www/html
